Release/WDSUS-2 V4.0
WebDevStudios/wd_s pull request #1023
Opened 2023-06-01 15:56 UTC by khleomix

# Closes
#WDSUS-2

## What type of PR is this? (put an x to all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [x] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [x] ✅ Test
- [x] 🤖 Build
- [x] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert

## Link to test
[Develop](https://wds-revamp.wdslab.com/)

## Description
- Bump packages:
  - Bump @wordpress/eslint-plugin from 14.4.0 to 14.7.0
  - Bump socket.io-parser from 4.2.2 to 4.2.3
  - Bump @evilmartians/lefthook from 1.3.13 to 1.4.1
  - Bump postcss-preset-env from 8.3.2 to 8.4.1
  - Bump browser-sync from 2.29.2 to 2.29.3
  - Bump glob from 10.2.4 to 10.2.6
- Update NPM from 16 to 18
- WDSUS-19: Add WDS Blocks Category
- 

## Related Tickets & Documents
- WDSUS-7
- WDSUS-10
- WDSUS-11
- WDSUS-16
- WDSUS-18
- WDSUS-19
- WDSUS-22
- WDSUS-25

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 [Confluence](https://webdevstudios.atlassian.net/wiki/spaces/wds1/pages/2988474566/Feature+Documentation)
- [ ] 🙅 no documentation needed

## Others

- [x] 🦮 Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] 🙌 Does this issue pass all the linting? (PHPCS, ESLint, SassLint)

## [optional] Are there any post-deployment tasks we need to perform?

2023-09-18 21:03 UTC, asharirfan requested changes

2023-09-18 21:03 UTC, asharirfan commented on assets/scss/critical/index.scss
> +@import 'footer';
@khleomix I don't think we need to include the _footer_ in critical CSS. Because it is only for the sections above the fold.

2023-09-18 21:03 UTC, asharirfan commented on inc/hooks/register-block-pattern-category.php
> +function wd_s_register_block_pattern_category() {
@khleomix No need to use the prefix `wd_s_` before function name because this function is already present in a wd_s namespace.

2023-09-18 21:03 UTC, asharirfan commented on inc/wpcli/class-blocks-scaffold.php
> +add_action( 'init', __NAMESPACE__ . '\wds_acf_register_blocks' );
@khleomix No need to use the prefix `wds_` before function name because this function is already present in a wd_s namespace.

2023-09-18 21:03 UTC, asharirfan commented on lefthook.yml
> +            exclude: 'group_*.json'  # Exclude specific files
@khleomix We should also exclude `package-lock.json` and `composer-lock.json` files.

2023-09-29 15:23 UTC, thatmitchcanter approved these changes
Everything looks solid. Approved ✅ Thanks for all your work on this!

2023-09-29 19:55 UTC, merged