Feature/code tweaks
WebDevStudios/wd_s pull request #312
Opened 2017-07-14 05:17 UTC by kellenmace

Rejigger a few little things in the functions & template tags files.

2017-07-14 13:05 UTC, gregrickaby commented
@kellenmace You're PR contains PHP errors. Can you please fix and resubmit? Thanks!

2017-07-15 04:15 UTC, kellenmace commented
@gregrickaby Thanks for the heads up! Pushed a fix and looks like all the Travis checks are passing now 👍🏼

2017-07-17 17:35 UTC, gregrickaby commented on inc/template-tags.php
> + * Get the Twitter social sharing URL for the current page.
@kellenmace Honest question, Do you think these getters should be moved to `extras.php` or maybe `queries.php`?

I'd like to keep `template-tags.php` as lean as possible...

2017-07-18 12:20 UTC, kellenmace commented
@gregrickaby What do you think about moving the markup in `_s_display_social_icons()` into a `content-social-icons.php` template part like in my last commit? Since that function doesn't take any parameters and just immediately outputs markup, it seems like it's a perfect candidate to be moved into a template part. And if we do that, I think it makes sense to leave the functions for getting the share URLs in `template-tags.php`, since they themselves would be template tags. Whatchu think?

2017-07-18 13:54 UTC, gregrickaby commented
@kellenmace Sounds good to me. Let me share this with the FEDs on today's scrum! Thanks for your PR dude! 👍

2017-07-18 16:03 UTC, kellenmace commented
woo hoooo - thanks. Welcome!

2017-07-19 14:44 UTC, gregrickaby requested changes
@kellenmace After speaking with the group, can you rename the template part to: `sharing-icons.php`

2017-07-19 15:36 UTC, gregrickaby approved these changes

2017-07-19 15:36 UTC, merged