Feature/389 webpack
WebDevStudios/wd_s pull request #432
Opened 2018-10-26 19:52 UTC by gregrickaby

Closes #389 

### DESCRIPTION ###

This is based on #402, which seems to be 

- [x] Drop sass-lint for stylelint
- [x] Update to Babel 7
- [x] Drop Sass Docs
- [x] I want linting to happen with each compile (see my example Webpack config, it does this)
- [x] BrowserSync stays!
- [x] NPM scripts all they way
- [x] Move browerlist to package.json
- [x] Update our linting configs to match WDS Code Standards
- [x] Added support for CSS Media Packer https://github.com/hail2u/node-css-mqpacker
- [x] NPM command added to build pot file
- [x] Support for spritesmith to generate image sprites added to webpack
- [x] minify images like gulp task
- [x] minify svgs like gulp task
- [x] generate svg icons sprite 
- [x] Added minification for JS on `npm build`

### SCREENSHOTS ###

### OTHER ###
- [ ] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [ ] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [ ] Does this pass CBT?

### STEPS TO VERIFY ###
How do we test this?

### DOCUMENTATION ###
Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?

2018-11-07 20:37 UTC, mharis commented
- Worked on small improvements
- Spent time trying to figure out why browsersync keeps reloading. Maybe it needs to use webpack-dev-server.

2018-11-23 20:00 UTC, aaroneaton commented
I got the eslint action fixed up. It was attempting to check a directory that didn't exist. Here's what the command is now in Buddy: `eslint './assets/scripts' --fix --debug --ignore-pattern lib/`

2018-11-29 20:28 UTC, coreymcollins requested changes
I started testing this a bit today and have run into two items so far which I've noted with file comments. I've also asked Haris to put together a testing plan so we can test this out as robustly as possible, making sure we don't miss any updated features or anything like that.

So far, general Sass compiling is working well though I know we had talked about removing the need for a `rem()` mixin or limitations on what unit types could be used in our partials, instead, saving that for compiling. I thought that was going to be a part of this update as well, but maybe not? Currently, if I try to use something like a pixel value for padding instead of the `rem()` mixin, I'll get a compilation error.

Do we want to roll that in here or should that be reserved for another update?

2018-11-29 20:28 UTC, coreymcollins commented on assets/scripts/index.js
> +import './components/header-button.js';
Missing `accordion.js`. I had tried editing each of the files and the Accordion file would not compile on save.

2018-11-29 20:28 UTC, coreymcollins commented on webpack.config.js
> +					image: path.resolve( __dirname, 'assets/images/sprites.png' ),
This doesn't appear to be working. I've saved a couple of `.png` files in the `/assets/images/sprites/` directory and while it looks like webpack is doing something, the `assets/images/sprites.png` file is never updated.

2018-12-07 12:36 UTC, mharis commented on assets/scripts/index.js
> +import './components/header-button.js';
I had no such issue @coreymcollins. This is from compiled JS file. https://www.dropbox.com/s/cnytz9av853ipy9/Screenshot%202018-12-07%2017.35.12.png?dl=0

Each component module has to be imported within the entry point to be compiled by webpack. Our entry point for webpack is `assets/scripts/index.js`

2018-12-07 13:20 UTC, mharis commented on webpack.config.js
> +					image: path.resolve( __dirname, 'assets/images/sprites.png' ),
Yes, there was a small bug which took a while to fix but it is fixed now and pushed.

2018-12-07 18:04 UTC, mharis commented
Passing this to @efuller for help. I am able to fix all the bugs I came across today except for this issue where I cannot make `url()` in sass files relative to the root of the theme folder. I'm not sure where I'm wrong and burnt out spending last 2 hours fixing this.

![screenshot 2018-12-07 23 00 31](https://user-images.githubusercontent.com/601054/49664598-26dd7c80-fa74-11e8-9cb7-bab671328375.png)

In the screenshot, URL is relative to the root of the website URL because it starts with a leading slash.

2019-01-02 22:28 UTC, efuller commented
Did some investigating on the image issue and I have one working solution in place, but want to do some more exploring of options. 

I think the main thing I'm taking away here is that we may need to change up the URL we use when including images into our CSS. I also think we will need to make sure images are emitted over to the dist folder.

Getting close, but not quite there yet!

2019-01-24 20:11 UTC, coreymcollins commented
@efuller & @mharis – do we still need this PR open with the existence of #452?

2019-11-13 20:37 UTC, closed without merging