Update phpcs ignore statements
WebDevStudios/wd_s pull request #605
Opened 2021-03-17 17:42 UTC by bradp

Closes #581

### DESCRIPTION

Updates phpcs:ignore to use correct format.

2021-03-18 13:31 UTC, jrfoell requested changes

2021-03-18 13:31 UTC, jrfoell commented on comments.php
> +				printf( // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Thanks for submitting this @bradp - can you keep the comments with your new ignores? ala:
```suggestion
				printf( // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- XSS OK.
```

2021-03-18 13:57 UTC, bradp commented
Updated. Also moved most of the ignore statements to the line before to make it easier to read.

2021-03-18 14:58 UTC, jrfoell approved these changes

2021-03-19 16:36 UTC, coreymcollins approved these changes

2021-03-19 16:37 UTC, merged