updated various dependencies and add support for php 8.0
WebDevStudios/wd_s pull request #913
Opened 2022-07-29 16:26 UTC by iamahless

Closes #912 

### DESCRIPTION

With the security updates on PHP 7.4 ending soon, the theme has been updated to work on PHP 8.0 and PHP 8.1 environments

### SCREENSHOTS

No screenshots.

### OTHER

- [ ] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [ ] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [ ] Does this pass CBT?

### STEPS TO VERIFY

Run npm run lint - there should be no errors.

### DOCUMENTATION

Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?

2022-08-15 21:09 UTC, bplv112 commented
I am still reviewing this PR. 
I am having some problems on my machine when using php 7.x I can't build the theme.
But shouldn't we be providing backward compatibility to php 7.X since it's not "that old" - Just a thought. 
Other than that everything looks good and working. 

cc: @asharirfan  @oliverharrison

2022-10-06 13:40 UTC, jrfoell requested changes
One addition I would make is bumping the minimum PHP version to 7.4 here: https://github.com/WebDevStudios/wd_s/blob/277a247cca20fa2d69daa70c0e34c019587a6ed4/phpcs.xml.dist#L68

2022-10-06 14:00 UTC, jrfoell approved these changes

2023-05-19 20:51 UTC, khleomix commented
Closing, this has been resolved with the latest release: https://github.com/WebDevStudios/wd_s/releases/tag/v3.5

2023-05-19 20:51 UTC, closed without merging