Feature/weng-226-setup-grid
WebDevStudios/wd_s pull request #938
Opened 2022-10-05 18:49 UTC by itsamoreh

Closes #\_\_

### DESCRIPTION

- What did you do? Give us some context...

### SCREENSHOTS

![screenshot](https://dl.dropbox.com/s/8k8xh3tuj3g5340/wd_s-pr-template.jpg?dl=0)

### OTHER

- [ ] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [ ] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [ ] Does this pass CBT?

### STEPS TO VERIFY

How do we test this?

### DOCUMENTATION

Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?

2022-10-13 19:31 UTC, webdevstudios-hosting requested changes
Just a couple suggestions.

2022-10-13 19:31 UTC, webdevstudios-hosting commented on template-parts/content.php
> +	<header class="entry-header container">
```suggestion
	<header class="entry-header">
```

Container is already applied.

2022-10-13 19:31 UTC, webdevstudios-hosting commented on template-parts/content.php
> +	<footer class="entry-footer container">
```suggestion
	<footer class="entry-footer">
```

Container is already applied

2022-10-14 13:23 UTC, oliverharrison approved these changes
This looks good to me.

2022-10-14 13:24 UTC, oliverharrison approved these changes

2022-10-14 13:25 UTC, merged